//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSprojekt.WebServisKarta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServisKarta.KartaSoap")]
    public interface KartaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiLokacijuKlijenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double[] DohvatiLokacijuKlijenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiLokacijuKlijenta", ReplyAction="*")]
        System.Threading.Tasks.Task<double[]> DohvatiLokacijuKlijentaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiAktivnosti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DohvatiAktivnosti(int radijus, string aktivnost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiAktivnosti", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DohvatiAktivnostiAsync(int radijus, string aktivnost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiSlikeAktivnosti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bitmap[]))]
        RSprojekt.WebServisKarta.Bitmap[] DohvatiSlikeAktivnosti(string response, string aktivnost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiSlikeAktivnosti", ReplyAction="*")]
        System.Threading.Tasks.Task<RSprojekt.WebServisKarta.Bitmap[]> DohvatiSlikeAktivnostiAsync(string response, string aktivnost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiLokacijeAktivnosti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bitmap[]))]
        double[] DohvatiLokacijeAktivnosti(string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DohvatiLokacijeAktivnosti", ReplyAction="*")]
        System.Threading.Tasks.Task<double[]> DohvatiLokacijeAktivnostiAsync(string response);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bitmap : Image {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bitmap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Image : MarshalByRefObject {
        
        private object tagField;
        
        private ColorPalette paletteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ColorPalette Palette {
            get {
                return this.paletteField;
            }
            set {
                this.paletteField = value;
                this.RaisePropertyChanged("Palette");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ColorPalette : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Image))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bitmap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KartaSoapChannel : RSprojekt.WebServisKarta.KartaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KartaSoapClient : System.ServiceModel.ClientBase<RSprojekt.WebServisKarta.KartaSoap>, RSprojekt.WebServisKarta.KartaSoap {
        
        public KartaSoapClient() {
        }
        
        public KartaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KartaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KartaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KartaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double[] DohvatiLokacijuKlijenta() {
            return base.Channel.DohvatiLokacijuKlijenta();
        }
        
        public System.Threading.Tasks.Task<double[]> DohvatiLokacijuKlijentaAsync() {
            return base.Channel.DohvatiLokacijuKlijentaAsync();
        }
        
        public string DohvatiAktivnosti(int radijus, string aktivnost) {
            return base.Channel.DohvatiAktivnosti(radijus, aktivnost);
        }
        
        public System.Threading.Tasks.Task<string> DohvatiAktivnostiAsync(int radijus, string aktivnost) {
            return base.Channel.DohvatiAktivnostiAsync(radijus, aktivnost);
        }
        
        public RSprojekt.WebServisKarta.Bitmap[] DohvatiSlikeAktivnosti(string response, string aktivnost) {
            return base.Channel.DohvatiSlikeAktivnosti(response, aktivnost);
        }
        
        public System.Threading.Tasks.Task<RSprojekt.WebServisKarta.Bitmap[]> DohvatiSlikeAktivnostiAsync(string response, string aktivnost) {
            return base.Channel.DohvatiSlikeAktivnostiAsync(response, aktivnost);
        }
        
        public double[] DohvatiLokacijeAktivnosti(string response) {
            return base.Channel.DohvatiLokacijeAktivnosti(response);
        }
        
        public System.Threading.Tasks.Task<double[]> DohvatiLokacijeAktivnostiAsync(string response) {
            return base.Channel.DohvatiLokacijeAktivnostiAsync(response);
        }
    }
}
